### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by OneMoreByte** [seanauff/Fanimation-RF-Controller#2]
Hey man! Looks like you did something a while back I was hoping to achieve. What fanimation remote did you write this code for? Do you know if there's much different between them? Also what radio did you use?

Thanks!
Jack

**Comment by seanauff** [comment]
Hey there! Sorry I don't have more documentation on this project!

The remote is Model RH787T, and I only know about this one.

As for the transmitter, I used a generic 315 MHz TX module, and replaced the resonator with a 304 MHz one.

Hope this helps!
