### ISSUE TITLE
What RF module did you used?

### ISSUE THREAD

**Issue by starwolf73** [seanauff/Fanimation-RF-Controller#3]
Hi,
Not sure where to ask this question, but what RF Module did you used? 

So far I only found RF module 315mhz and I need to control a fan on 304mhz so you rep interest me a lot. 

thanks

**Comment by seanauff** [comment]
I used a generic 315 MHz TX module, and replaced the resonator with a 304 MHz one. I could only find SMD ones so it was a bit of a pain but it works!
